name: next-js-template-app
services:
  web-app:
    build: ..\web-app
    image: next-js-template-webapp
    container_name: webapp
    ports:
      - "2222:22"
      - "3001:3000"
    volumes:
      - ./webapp/supervisor:/etc/supervisor

  webapp-db-postgres:
    image: postgres:16
    container_name: webapp-db-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: next-js-template
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  wordpress-db-mysql:
    image: mysql:9.2.0
    container_name: wordpress-db-mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - wordpress_db_data:/var/lib/mysql

  postgres-db-admin:
    image: dpage/pgadmin4:latest
    container_name: pg-db-admin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@postgres.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    volumes:
      - ./postgres/pg-servers.json:/pgadmin4/servers.json
      - ./postgres/pgpass:/pgpass
    depends_on:
      - webapp-db-postgres

  wordpress:
    image: wordpress:6.7.1
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-db-mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress-db-mysql

  ansible:
    build: ./ansible
    container_name: ansible
    command: /bin/bash
    tty: true
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    ports:
      - "2223:22"
    volumes:
      - ../web-app:/home/nextjs/nextjs-app/web-app
      - ./ansible/playbooks:/home/nextjs/ansible/playbooks

volumes:
  wordpress_data:
  wordpress_db_data:
