name: next-js-template-app
services:
  web-app:
    build: ..\web-app
    image: next-js-template-webapp
    container_name: webapp
    ports:
      - "2222:22"
      - "3001:3000"
    volumes:
      - ./webapp/supervisor:/etc/supervisor
  postgres-db:
    image: postgres:16
    container_name: pg-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: next-js-template
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
  postgres-db-admin:
    image: dpage/pgadmin4:latest
    container_name: pg-db-admin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@postgres.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    volumes:
      - ./postgres/pg-servers.json:/pgadmin4/servers.json
      - ./postgres/pgpass:/pgpass
  ansible:
    build: ./ansible
    container_name: ansible
    command: /bin/bash
    tty: true
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    ports:
      - "2223:22"
    volumes:
      - ../web-app:/home/nextjs/nextjs-app/web-app
      - ./ansible/playbooks:/home/nextjs/ansible/playbooks
